project:
  output-dir: ../docs

author:
  - name: Daniel Nguyen
    email: nguyend35@vcu.edu
  - name: Carter DuBois
    email: duboisch@vcu.edu

format:
  html:
    toc: true
    embed-resources: true
    html-math-method: katex
    theme: cosmo
